-- Лоты аукциона: публичное чтение, изменение только администратором сайта.
create table if not exists public.auction_items (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 120),
  description text not null default '' check (char_length(description) <= 240),
  amount numeric(12,2) not null default 0 check (amount >= 0),
  display_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.auction_items enable row level security;
revoke all on table public.auction_items from anon, authenticated;
grant select on table public.auction_items to anon, authenticated;
grant insert, update, delete on table public.auction_items to authenticated;
grant usage, select on sequence public.auction_items_id_seq to authenticated;

drop policy if exists "auction items are public" on public.auction_items;
create policy "auction items are public" on public.auction_items for select to anon, authenticated using (active = true or public.is_site_admin());

drop policy if exists "admins manage auction items" on public.auction_items;
create policy "admins manage auction items" on public.auction_items for all to authenticated using (public.is_site_admin()) with check (public.is_site_admin());

alter table public.auction_items add column if not exists eliminated boolean not null default false;
