-- ПРЕДЛОЖКА141 — предложения зрителей, рейтинг и комментарии.
-- Выполни файл целиком в Supabase SQL Editor после базового supabase_setup.sql.
-- Для действий зрителей включи Authentication -> Providers -> Anonymous Sign-Ins.

create table if not exists public.game_suggestions (
  id bigint generated by default as identity primary key,
  steam_app_id bigint not null unique check (steam_app_id > 0),
  steam_url text not null check (char_length(steam_url) between 20 and 500),
  title text not null check (char_length(title) between 1 and 120),
  cover_url text not null default '' check (char_length(cover_url) <= 1000),
  description text not null default '' check (char_length(description) <= 2000),
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'selected', 'completed', 'archived')),
  rejection_reason text not null default '' check (char_length(rejection_reason) <= 500),
  submitted_by uuid default auth.uid() references auth.users(id) on delete set null,
  moderated_by uuid references auth.users(id) on delete set null,
  moderated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.suggestion_supports (
  suggestion_id bigint not null references public.game_suggestions(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (suggestion_id, user_id)
);

create table if not exists public.suggestion_votes (
  suggestion_id bigint not null references public.game_suggestions(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (suggestion_id, user_id)
);

create table if not exists public.suggestion_comments (
  id bigint generated by default as identity primary key,
  suggestion_id bigint not null references public.game_suggestions(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  body text not null check (char_length(btrim(body)) between 1 and 300),
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (suggestion_id, user_id)
);

create index if not exists game_suggestions_status_created_idx
  on public.game_suggestions (status, created_at desc);
create index if not exists suggestion_supports_suggestion_idx
  on public.suggestion_supports (suggestion_id);
create index if not exists suggestion_votes_suggestion_idx
  on public.suggestion_votes (suggestion_id);
create index if not exists suggestion_comments_suggestion_created_idx
  on public.suggestion_comments (suggestion_id, created_at);

drop trigger if exists game_suggestions_set_updated_at on public.game_suggestions;
create trigger game_suggestions_set_updated_at
before update on public.game_suggestions
for each row execute function public.set_updated_at();

drop trigger if exists suggestion_comments_set_updated_at on public.suggestion_comments;
create trigger suggestion_comments_set_updated_at
before update on public.suggestion_comments
for each row execute function public.set_updated_at();

alter table public.game_suggestions enable row level security;
alter table public.suggestion_supports enable row level security;
alter table public.suggestion_votes enable row level security;
alter table public.suggestion_comments enable row level security;

revoke all on table public.game_suggestions from anon, authenticated;
revoke all on table public.suggestion_supports from anon, authenticated;
revoke all on table public.suggestion_votes from anon, authenticated;
revoke all on table public.suggestion_comments from anon, authenticated;

grant select, update on table public.game_suggestions to authenticated;
grant select on table public.suggestion_supports to authenticated;
grant select on table public.suggestion_votes to authenticated;
grant select, update on table public.suggestion_comments to authenticated;

drop policy if exists "Admins can read suggestions" on public.game_suggestions;
create policy "Admins can read suggestions"
on public.game_suggestions for select to authenticated
using ((select public.is_site_admin()));

drop policy if exists "Admins can update suggestions" on public.game_suggestions;
create policy "Admins can update suggestions"
on public.game_suggestions for update to authenticated
using ((select public.is_site_admin()))
with check ((select public.is_site_admin()));

drop policy if exists "Admins can read suggestion supports" on public.suggestion_supports;
create policy "Admins can read suggestion supports"
on public.suggestion_supports for select to authenticated
using ((select public.is_site_admin()));

drop policy if exists "Admins can read suggestion votes" on public.suggestion_votes;
create policy "Admins can read suggestion votes"
on public.suggestion_votes for select to authenticated
using ((select public.is_site_admin()));

drop policy if exists "Admins can read suggestion comments" on public.suggestion_comments;
create policy "Admins can read suggestion comments"
on public.suggestion_comments for select to authenticated
using ((select public.is_site_admin()));

drop policy if exists "Admins can moderate suggestion comments" on public.suggestion_comments;
create policy "Admins can moderate suggestion comments"
on public.suggestion_comments for update to authenticated
using ((select public.is_site_admin()))
with check ((select public.is_site_admin()));

create or replace function public.submit_game_suggestion(
  p_steam_app_id bigint,
  p_title text,
  p_cover_url text default '',
  p_description text default '',
  p_comment text default ''
)
returns table (
  suggestion_id bigint,
  suggestion_status text,
  was_created boolean,
  support_count bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_suggestion public.game_suggestions;
  v_created boolean := false;
  v_comment text := btrim(coalesce(p_comment, ''));
begin
  if v_user_id is null then
    raise exception 'Требуется авторизация зрителя.';
  end if;
  if p_steam_app_id is null or p_steam_app_id <= 0 then
    raise exception 'Некорректный Steam App ID.';
  end if;
  if char_length(btrim(coalesce(p_title, ''))) not between 1 and 120 then
    raise exception 'Некорректное название игры.';
  end if;
  if char_length(coalesce(p_cover_url, '')) > 1000
    or char_length(coalesce(p_description, '')) > 2000
    or char_length(v_comment) > 300 then
    raise exception 'Слишком длинные данные предложения.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(p_steam_app_id);

  select *
    into v_suggestion
    from public.game_suggestions
   where steam_app_id = p_steam_app_id
   for update;

  if not found then
    if (
      select count(*)
      from public.game_suggestions
      where submitted_by = v_user_id
        and created_at >= now() - interval '24 hours'
    ) >= 5 then
      raise exception 'Можно предложить не больше пяти новых игр за 24 часа.';
    end if;

    insert into public.game_suggestions (
      steam_app_id, steam_url, title, cover_url, description, submitted_by
    )
    values (
      p_steam_app_id,
      'https://store.steampowered.com/app/' || p_steam_app_id || '/',
      btrim(p_title),
      coalesce(p_cover_url, ''),
      coalesce(p_description, ''),
      v_user_id
    )
    returning * into v_suggestion;
    v_created := true;
  end if;

  if v_suggestion.status = 'pending' then
    insert into public.suggestion_supports (suggestion_id, user_id)
    values (v_suggestion.id, v_user_id)
    on conflict do nothing;
  end if;

  if v_comment <> '' and v_suggestion.status in ('pending', 'approved', 'selected') then
    insert into public.suggestion_comments (suggestion_id, user_id, body)
    values (v_suggestion.id, v_user_id, v_comment)
    on conflict (suggestion_id, user_id)
    do update set body = excluded.body, is_hidden = false, updated_at = now();
  end if;

  return query
  select
    v_suggestion.id,
    v_suggestion.status,
    v_created,
    (select count(*) from public.suggestion_supports s where s.suggestion_id = v_suggestion.id);
end;
$$;

create or replace function public.get_public_game_suggestions()
returns table (
  id bigint,
  steam_app_id bigint,
  steam_url text,
  title text,
  cover_url text,
  description text,
  status text,
  created_at timestamptz,
  support_count bigint,
  vote_count bigint,
  comment_count bigint,
  has_supported boolean,
  has_voted boolean,
  my_comment text
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    g.id,
    g.steam_app_id,
    g.steam_url,
    g.title,
    g.cover_url,
    g.description,
    g.status,
    g.created_at,
    (select count(*) from public.suggestion_supports s where s.suggestion_id = g.id),
    (select count(*) from public.suggestion_votes v where v.suggestion_id = g.id),
    (select count(*) from public.suggestion_comments c where c.suggestion_id = g.id and not c.is_hidden),
    exists (
      select 1 from public.suggestion_supports s
      where s.suggestion_id = g.id and s.user_id = auth.uid()
    ),
    exists (
      select 1 from public.suggestion_votes v
      where v.suggestion_id = g.id and v.user_id = auth.uid()
    ),
    coalesce((
      select c.body from public.suggestion_comments c
      where c.suggestion_id = g.id and c.user_id = auth.uid()
      limit 1
    ), '')
  from public.game_suggestions g
  where g.status in ('approved', 'selected')
  order by
    (g.status = 'selected') desc,
    (select count(*) from public.suggestion_votes v where v.suggestion_id = g.id) desc,
    g.created_at asc;
$$;

create or replace function public.get_public_suggestion_comments(p_suggestion_id bigint)
returns table (
  id bigint,
  body text,
  created_at timestamptz,
  updated_at timestamptz,
  is_mine boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  select c.id, c.body, c.created_at, c.updated_at, c.user_id = auth.uid()
  from public.suggestion_comments c
  join public.game_suggestions g on g.id = c.suggestion_id
  where c.suggestion_id = p_suggestion_id
    and not c.is_hidden
    and g.status in ('approved', 'selected')
  order by c.created_at asc;
$$;

create or replace function public.toggle_suggestion_vote(p_suggestion_id bigint)
returns table (active boolean, vote_count bigint)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_active boolean;
begin
  if v_user_id is null then raise exception 'Требуется авторизация зрителя.'; end if;
  if not exists (
    select 1 from public.game_suggestions
    where id = p_suggestion_id and status = 'approved'
  ) then
    raise exception 'Голосование за эту игру закрыто.';
  end if;

  delete from public.suggestion_votes
  where suggestion_id = p_suggestion_id and user_id = v_user_id;

  if found then
    v_active := false;
  else
    insert into public.suggestion_votes (suggestion_id, user_id)
    values (p_suggestion_id, v_user_id);
    v_active := true;
  end if;

  return query
  select
    v_active,
    (select count(*) from public.suggestion_votes where suggestion_id = p_suggestion_id);
end;
$$;

create or replace function public.upsert_suggestion_comment(
  p_suggestion_id bigint,
  p_body text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_body text := btrim(coalesce(p_body, ''));
  v_id bigint;
begin
  if v_user_id is null then raise exception 'Требуется авторизация зрителя.'; end if;
  if char_length(v_body) not between 1 and 300 then
    raise exception 'Комментарий должен содержать от 1 до 300 символов.';
  end if;
  if not exists (
    select 1 from public.game_suggestions
    where id = p_suggestion_id and status in ('approved', 'selected')
  ) then
    raise exception 'Комментарии для этой игры закрыты.';
  end if;

  insert into public.suggestion_comments (suggestion_id, user_id, body)
  values (p_suggestion_id, v_user_id, v_body)
  on conflict (suggestion_id, user_id)
  do update set body = excluded.body, is_hidden = false, updated_at = now()
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.delete_my_suggestion_comment(p_suggestion_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then raise exception 'Требуется авторизация зрителя.'; end if;
  delete from public.suggestion_comments
  where suggestion_id = p_suggestion_id and user_id = auth.uid();
  return found;
end;
$$;

create or replace function public.moderate_game_suggestion(
  p_suggestion_id bigint,
  p_action text,
  p_reason text default ''
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_status text;
begin
  if not public.is_site_admin() then raise exception 'Недостаточно прав.'; end if;

  v_status := case p_action
    when 'approve' then 'approved'
    when 'reject' then 'rejected'
    when 'select' then 'selected'
    when 'complete' then 'completed'
    when 'archive' then 'archived'
    when 'reopen' then 'approved'
    else null
  end;
  if v_status is null then raise exception 'Неизвестное действие модерации.'; end if;

  if v_status = 'selected' then
    update public.game_suggestions
       set status = 'approved', moderated_at = now(), moderated_by = auth.uid()
     where status = 'selected' and id <> p_suggestion_id;
  end if;

  update public.game_suggestions
     set status = v_status,
         rejection_reason = case when v_status = 'rejected' then left(btrim(coalesce(p_reason, '')), 500) else '' end,
         moderated_at = now(),
         moderated_by = auth.uid()
   where id = p_suggestion_id;
  if not found then raise exception 'Предложение не найдено.'; end if;
  return v_status;
end;
$$;

create or replace function public.moderate_suggestion_comment(
  p_comment_id bigint,
  p_hidden boolean
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_site_admin() then raise exception 'Недостаточно прав.'; end if;
  update public.suggestion_comments set is_hidden = p_hidden where id = p_comment_id;
  return found;
end;
$$;

revoke all on function public.submit_game_suggestion(bigint, text, text, text, text) from public;
revoke all on function public.get_public_game_suggestions() from public;
revoke all on function public.get_public_suggestion_comments(bigint) from public;
revoke all on function public.toggle_suggestion_vote(bigint) from public;
revoke all on function public.upsert_suggestion_comment(bigint, text) from public;
revoke all on function public.delete_my_suggestion_comment(bigint) from public;
revoke all on function public.moderate_game_suggestion(bigint, text, text) from public;
revoke all on function public.moderate_suggestion_comment(bigint, boolean) from public;

grant execute on function public.get_public_game_suggestions() to anon, authenticated;
grant execute on function public.get_public_suggestion_comments(bigint) to anon, authenticated;
grant execute on function public.submit_game_suggestion(bigint, text, text, text, text) to authenticated;
grant execute on function public.toggle_suggestion_vote(bigint) to authenticated;
grant execute on function public.upsert_suggestion_comment(bigint, text) to authenticated;
grant execute on function public.delete_my_suggestion_comment(bigint) to authenticated;
grant execute on function public.moderate_game_suggestion(bigint, text, text) to authenticated;
grant execute on function public.moderate_suggestion_comment(bigint, boolean) to authenticated;

do $$
declare
  v_table text;
begin
  foreach v_table in array array[
    'game_suggestions',
    'suggestion_supports',
    'suggestion_votes',
    'suggestion_comments'
  ]
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = v_table
    ) then
      execute format('alter publication supabase_realtime add table public.%I', v_table);
    end if;
  end loop;
end $$;
