-- Оценки и комментарии к играм каталога по новому макету Figma.
-- Выполните файл целиком после supabase/game_reputation.sql.

create table if not exists public.game_comments (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(btrim(body)) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists game_comments_game_created_idx
  on public.game_comments (game_id, created_at desc);

alter table public.game_comments enable row level security;
revoke all on table public.game_comments from anon, authenticated;

drop function if exists public.get_game_vote_scores();
create function public.get_game_vote_scores()
returns table (
  game_id bigint,
  score bigint,
  like_count bigint,
  dislike_count bigint,
  reaction_count bigint
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    g.id,
    coalesce(sum(v.vote), 0)::bigint,
    count(v.user_id) filter (where v.vote = 1)::bigint,
    count(v.user_id) filter (where v.vote = -1)::bigint,
    count(v.user_id)::bigint
  from public.games g
  left join public.game_votes v on v.game_id = g.id
  where g.published = true
  group by g.id;
$$;

create or replace function public.get_my_game_votes()
returns table (game_id bigint, vote smallint)
language sql
stable
security definer
set search_path = ''
as $$
  select v.game_id, v.vote
  from public.game_votes v
  where v.user_id = (select auth.uid());
$$;

create or replace function public.set_game_reaction(p_game_id bigint, p_reaction smallint)
returns table (
  current_reaction smallint,
  score bigint,
  like_count bigint,
  dislike_count bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  viewer_id uuid := auth.uid();
  previous_reaction smallint;
  next_reaction smallint;
begin
  if viewer_id is null then
    raise exception 'Требуется авторизация.' using errcode = '42501';
  end if;
  if p_reaction not in (-1, 1) then
    raise exception 'Реакция должна быть лайком или дизлайком.' using errcode = '22023';
  end if;
  if not exists (select 1 from public.games where id = p_game_id and published = true) then
    raise exception 'Игра не найдена.' using errcode = 'P0002';
  end if;

  select vote into previous_reaction
  from public.game_votes
  where game_id = p_game_id and user_id = viewer_id;

  if previous_reaction = p_reaction then
    delete from public.game_votes where game_id = p_game_id and user_id = viewer_id;
    next_reaction := 0;
  else
    insert into public.game_votes (game_id, user_id, vote)
    values (p_game_id, viewer_id, p_reaction)
    on conflict (game_id, user_id) do update
      set vote = excluded.vote, updated_at = now();
    next_reaction := p_reaction;
  end if;

  return query
  select
    next_reaction,
    coalesce(sum(v.vote), 0)::bigint,
    count(*) filter (where v.vote = 1)::bigint,
    count(*) filter (where v.vote = -1)::bigint
  from public.game_votes v
  where v.game_id = p_game_id;
end;
$$;

create or replace function public.add_game_comment(p_game_id bigint, p_body text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  viewer_id uuid := auth.uid();
  clean_body text := btrim(coalesce(p_body, ''));
  new_id bigint;
begin
  if viewer_id is null then
    raise exception 'Требуется авторизация.' using errcode = '42501';
  end if;
  if char_length(clean_body) not between 1 and 500 then
    raise exception 'Комментарий должен содержать от 1 до 500 символов.';
  end if;
  if not exists (select 1 from public.games where id = p_game_id and published = true) then
    raise exception 'Игра не найдена.' using errcode = 'P0002';
  end if;
  insert into public.game_comments (game_id, user_id, body)
  values (p_game_id, viewer_id, clean_body)
  returning id into new_id;
  return new_id;
end;
$$;

create or replace function public.get_game_interactions(p_game_id bigint)
returns table (
  like_count bigint,
  dislike_count bigint,
  score bigint,
  my_reaction smallint,
  comment_id bigint,
  username text,
  comment_body text,
  comment_created_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  with stats as (
    select
      count(*) filter (where vote = 1)::bigint as likes,
      count(*) filter (where vote = -1)::bigint as dislikes,
      coalesce(sum(vote), 0)::bigint as score
    from public.game_votes
    where game_id = p_game_id
  ), mine as (
    select coalesce((
      select vote from public.game_votes
      where game_id = p_game_id and user_id = auth.uid()
    ), 0)::smallint as reaction
  )
  select
    stats.likes,
    stats.dislikes,
    stats.score,
    mine.reaction,
    c.id,
    coalesce(
      nullif(u.raw_user_meta_data ->> 'preferred_username', ''),
      nullif(u.raw_user_meta_data ->> 'full_name', ''),
      nullif(u.raw_user_meta_data ->> 'name', ''),
      split_part(coalesce(u.email, 'Пользователь'), '@', 1)
    ),
    c.body,
    c.created_at
  from stats
  cross join mine
  left join public.game_comments c on c.game_id = p_game_id
  left join auth.users u on u.id = c.user_id
  where exists (select 1 from public.games where id = p_game_id and published = true)
  order by c.created_at asc nulls last;
$$;

create or replace function public.delete_game_suggestion(p_suggestion_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or not public.is_site_admin() then
    raise exception 'Удалять предложения может только администратор.' using errcode = '42501';
  end if;
  delete from public.game_suggestions where id = p_suggestion_id;
  return found;
end;
$$;

revoke all on function public.get_game_vote_scores() from public;
revoke all on function public.get_my_game_votes() from public;
revoke all on function public.set_game_reaction(bigint, smallint) from public;
revoke all on function public.add_game_comment(bigint, text) from public;
revoke all on function public.get_game_interactions(bigint) from public;
revoke all on function public.delete_game_suggestion(bigint) from public;
grant execute on function public.get_game_vote_scores() to anon, authenticated;
grant execute on function public.get_my_game_votes() to authenticated;
grant execute on function public.set_game_reaction(bigint, smallint) to authenticated;
grant execute on function public.add_game_comment(bigint, text) to authenticated;
grant execute on function public.get_game_interactions(bigint) to anon, authenticated;
grant execute on function public.delete_game_suggestion(bigint) to authenticated;

notify pgrst, 'reload schema';
