-- ПРЕДЛОЖКА CR7 — схема Supabase
-- Запусти весь файл один раз в Supabase → SQL Editor.

create table if not exists public.site_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.site_admins enable row level security;
revoke all on table public.site_admins from anon, authenticated;

create or replace function public.is_site_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.site_admins
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_site_admin() from public;
grant execute on function public.is_site_admin() to authenticated;

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 120),
  steam_url text not null check (char_length(steam_url) <= 500),
  cover_url text not null default '' check (char_length(cover_url) <= 1000),
  description text not null check (char_length(description) between 1 and 2000),
  author_comment text not null default '' check (char_length(author_comment) <= 1200),
  display_order integer not null default 0 check (display_order between 0 and 9999),
  published boolean not null default true,
  library_status text not null default '' check (library_status in ('', 'completed', 'dropped', 'ignored')),
  is_favorite boolean not null default false,
  tier_rank text not null default '' check (tier_rank in ('', 'S', 'A', 'B', 'C', 'D')),
  tier_order integer not null default 0,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists games_set_updated_at on public.games;
create trigger games_set_updated_at
before update on public.games
for each row execute function public.set_updated_at();

alter table public.games enable row level security;

revoke all on table public.games from anon, authenticated;
revoke select on table public.games from anon, authenticated;
grant select (
  id,
  title,
  steam_url,
  cover_url,
  description,
  author_comment,
  display_order,
  published,
  library_status,
  is_favorite,
  tier_rank,
  tier_order,
  created_at,
  updated_at
) on table public.games to anon, authenticated;
grant insert, update, delete on table public.games to authenticated;
grant usage, select on sequence public.games_id_seq to authenticated;

-- Удаляем старые политики при повторном запуске скрипта.
drop policy if exists "Public can read published games" on public.games;
drop policy if exists "Admins can read all games" on public.games;
drop policy if exists "Admins can insert games" on public.games;
drop policy if exists "Admins can update games" on public.games;
drop policy if exists "Admins can delete games" on public.games;

create policy "Public can read published games"
on public.games
for select
to anon, authenticated
using (published = true);

create policy "Admins can read all games"
on public.games
for select
to authenticated
using ((select public.is_site_admin()));

create policy "Admins can insert games"
on public.games
for insert
to authenticated
with check (
  (select public.is_site_admin())
  and created_by = (select auth.uid())
);

create policy "Admins can update games"
on public.games
for update
to authenticated
using ((select public.is_site_admin()))
with check ((select public.is_site_admin()));

create policy "Admins can delete games"
on public.games
for delete
to authenticated
using ((select public.is_site_admin()));

-- Добавляем таблицу в Realtime-публикацию, если её там ещё нет.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'games'
  ) then
    alter publication supabase_realtime add table public.games;
  end if;
end $$;

-- ПОСЛЕ создания пользователя в Authentication → Users:
-- 1. Скопируй его UUID.
-- 2. Выполни отдельно строку ниже, заменив UUID:
-- insert into public.site_admins (user_id) values ('ТВОЙ-UUID-ПОЛЬЗОВАТЕЛЯ');

create table if not exists public.tier_list_settings (
  id smallint primary key default 1 check (id = 1),
  config jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);
alter table public.tier_list_settings enable row level security;
drop policy if exists "tier settings public read" on public.tier_list_settings;
create policy "tier settings public read" on public.tier_list_settings for select using (true);
drop policy if exists "tier settings admin insert" on public.tier_list_settings;
create policy "tier settings admin insert" on public.tier_list_settings for insert with check (public.is_site_admin());
drop policy if exists "tier settings admin update" on public.tier_list_settings;
create policy "tier settings admin update" on public.tier_list_settings for update using (public.is_site_admin()) with check (public.is_site_admin());
insert into public.tier_list_settings (id,config) values (1,'[]'::jsonb) on conflict (id) do nothing;
